---
deployment:
  tasks:
    - export DEPLOYPATH=/var/www/u1384230/repositories/taraswww777.dev
    - npm ci
    - npm run deploy
    - /bin/cp ./out $DEPLOYPATH -r
    - /bin/cp ./deploy $DEPLOYPATH -r
