---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/taraswww777.dev-2
    - npm ci
    - npm run deploy
    - /bin/cp ./out $DEPLOYPATH -r
    - /bin/cp ./deploy $DEPLOYPATH -r
